language: r
sudo: false
env: _R_CHECK_CRAN_INCOMING_=FALSE
cache: packages

r:
  - oldrel
  - release
  - devel

r_github_packages:
  - jimhester/covr

after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
